#include "helpers.hpp"

#include <string>

std::string VkResultToString(VkResult result) {
#define CASE_STR(r) \
  case r:           \
    return #r

  switch (result) {
    CASE_STR(VK_SUCCESS);
    CASE_STR(VK_NOT_READY);
    CASE_STR(VK_TIMEOUT);
    CASE_STR(VK_EVENT_SET);
    CASE_STR(VK_EVENT_RESET);
    CASE_STR(VK_INCOMPLETE);
    CASE_STR(VK_ERROR_OUT_OF_HOST_MEMORY);
    CASE_STR(VK_ERROR_OUT_OF_DEVICE_MEMORY);
    CASE_STR(VK_ERROR_INITIALIZATION_FAILED);
    CASE_STR(VK_ERROR_DEVICE_LOST);
    CASE_STR(VK_ERROR_MEMORY_MAP_FAILED);
    CASE_STR(VK_ERROR_LAYER_NOT_PRESENT);
    CASE_STR(VK_ERROR_EXTENSION_NOT_PRESENT);
    CASE_STR(VK_ERROR_FEATURE_NOT_PRESENT);
    CASE_STR(VK_ERROR_INCOMPATIBLE_DRIVER);
    CASE_STR(VK_ERROR_TOO_MANY_OBJECTS);
    CASE_STR(VK_ERROR_FORMAT_NOT_SUPPORTED);
    CASE_STR(VK_ERROR_FRAGMENTED_POOL);
    CASE_STR(VK_ERROR_UNKNOWN);
    CASE_STR(VK_ERROR_OUT_OF_POOL_MEMORY);
    CASE_STR(VK_ERROR_INVALID_EXTERNAL_HANDLE);
    CASE_STR(VK_ERROR_FRAGMENTATION);
    CASE_STR(VK_ERROR_INVALID_OPAQUE_CAPTURE_ADDRESS);
    CASE_STR(VK_ERROR_SURFACE_LOST_KHR);
    CASE_STR(VK_ERROR_NATIVE_WINDOW_IN_USE_KHR);
    CASE_STR(VK_SUBOPTIMAL_KHR);
    CASE_STR(VK_ERROR_OUT_OF_DATE_KHR);
    CASE_STR(VK_ERROR_INCOMPATIBLE_DISPLAY_KHR);
    CASE_STR(VK_ERROR_VALIDATION_FAILED_EXT);
    CASE_STR(VK_ERROR_INVALID_SHADER_NV);
    CASE_STR(VK_ERROR_INVALID_DRM_FORMAT_MODIFIER_PLANE_LAYOUT_EXT);
    CASE_STR(VK_ERROR_NOT_PERMITTED_EXT);
    CASE_STR(VK_ERROR_FULL_SCREEN_EXCLUSIVE_MODE_LOST_EXT);
    CASE_STR(VK_THREAD_IDLE_KHR);
    CASE_STR(VK_THREAD_DONE_KHR);
    CASE_STR(VK_OPERATION_DEFERRED_KHR);
    CASE_STR(VK_OPERATION_NOT_DEFERRED_KHR);
    CASE_STR(VK_PIPELINE_COMPILE_REQUIRED_EXT);
    // CASE_STR(VK_ERROR_OUT_OF_POOL_MEMORY_KHR);
    // CASE_STR(VK_ERROR_INVALID_EXTERNAL_HANDLE_KHR);
    // CASE_STR(VK_ERROR_FRAGMENTATION_EXT);
    // CASE_STR(VK_ERROR_INVALID_DEVICE_ADDRESS_EXT);
    // CASE_STR(VK_ERROR_INVALID_OPAQUE_CAPTURE_ADDRESS_KHR);
    // CASE_STR(VK_ERROR_PIPELINE_COMPILE_REQUIRED_EXT);
    CASE_STR(VK_RESULT_MAX_ENUM);
    default:
      return std::to_string(result);
  }
#undef CASE_STR
}